name: app
type: php:5.6
build:
  flavor: composer
disk: 2048
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
mounts:
  "storage/logs": "shared:files/logs"
  "bootstrap/cache": "shared:files/bootstrap_cache"
  "storage/framework/sessions": "shared:files/sessions"
  "storage/framework/cache": "shared:files/cache"