name: app
type: php:7.0
runtime:
  extensions:
    - pdo_pgsql
    - redis
build:
  flavor: composer
disk: 2048
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
mounts:
  "/storage/app/public": "shared:files/public"
  "/storage/framework/views": "shared:files/views"
  "/storage/framework/sessions": "shared:files/sessions"
  "/storage/framework/cache": "shared:files/cache"
  "/storage/logs": "shared:files/logs"
  "/bootstrap/cache": "shared:files/bootstrap_cache"
  "public/uploads": "shared:files/uploads"
relationships:
  database: "pgsql:postgresql"
  db2: "pgsql96:postgresql"
  redis: "rediscache:redis"

dependencies:
  ruby:
    sass: "*"
  nodejs:
    gulp-cli: "*"
    yarn: "*"

hooks:
  build: |
    yarn install
    gulp default
  deploy: |
    php artisan migrate --force