name: app
type: php:7.0
runtime:
  extensions:
    - pdo_pgsql
    - redis
build:
  flavor: composer
disk: 4000
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
mounts:
  "storage/app/public": "shared:files/public"
  "storage/framework/views": "shared:files/views"
  "storage/framework/sessions": "shared:files/sessions"
  "storage/framework/cache": "shared:files/cache"
  "storage/logs": "shared:files/logs"
  "bootstrap/cache": "shared:files/bootstrap_cache"
  "public/uploads": "shared:files/uploads"
  "Dropbox": "shared:files/dropbox"
  ".dropbox": "shared:files/dropbox-meta"
relationships:
  database: "pgsql96:postgresql"
  redis: "rediscache:redis"
dependencies:
  ruby:
    sass: "*"
  nodejs:
    gulp-cli: "*"
    yarn: "*"
hooks:
  build: |
    yarn install
    gulp default
    gzip -k public/js/all.js
    gzip -k public/css/app.css
    wget "https://www.dropbox.com/download?plat=lnx.x86_64" -O archive.tar && tar xzvf archive.tar && rm archive.tar
  deploy: |
    nohup ~/.dropbox-dist/dropboxd >/dev/null 2>&1 &
    php artisan migrate --force