name: app
type: php:7.0
runtime:
  extensions:
    - pdo_pgsql
    - redis
build:
  flavor: composer
disk: 2048
web:
  locations:
    "/":
      root: "public"
      index:
        - index.php
      allow: true
      passthru: "/index.php"
mounts:
  "/storage/app/public": "shared:files/storage/app/public"
  "/storage/framework/views": "shared:files/storage/framework/views"
  "/storage/framework/sessions": "shared:files/storage/framework/sessions"
  "/storage/framework/cache": "shared:files/storage/framework/cache"
  "/storage/logs": "shared:files/logs"
  "/bootstrap/cache": "shared:files/bootstrap_cache"
relationships:
  database: "pgsql:postgresql"
  redis: "rediscache:redis"
hooks:
  build: |
    wget https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.0.tar.gz
    tar xzvf ncurses-6.0.tar.gz
    cd ncurses-6.0
    ./configure --prefix=$HOME
    make
    make install
    cd ~
    wget https://github.com/hishamhm/htop/archive/2.0.2.tar.gz
    tar xzvf 2.0.2.tar.gz
    cd htop-2.0.2
    ./autogen.sh && ./configure --help
    make install
  deploy: |
    php artisan migrate --force